#!/usr/bin/env python3

## `(buffer-name)`

################################################################################
# Copyright Abaco Systems, Inc. (`(format-time-string "%Y")`)
#
# All rights reserved. No part of this software may be re-produced,
# re-engineered, re-compiled, modified, used to create derivatives, stored in
# a retrieval system, or transmitted in any form or by any means, electronic,
# mechanical, photocopying, recording, or otherwise without the prior written
# permission of Abaco Systems, Inc.
#
#
# Script to $0
#
################################################################################
